### ISSUE TITLE
Deployment Issues/questions

### ISSUE THREAD

**Issue by scjohnmsft** [OfficeDev/microsoft-teams-apps-survey#1]
When following the deployment guide steps 4.1 & 5.1 to prepare the app the admin permission request related to https://actions.office365.com/ActionPackage.ReadWrite.All does this have something to do with the Kaizala service?

We understand there are two packages(action package and teams app) which has the following web application info about where the apps will be hosted once we deploy them. 

"webApplicationInfo": {
    "id": "**9bb724a5-4639-438c-969b-e184b2b1e264**",
    "resource": "https://actions.office365.com"
  }

The bolded id above is the APPID of KaizalaActionsPlatform (https://www.rickvanrousselt.com/azure-default-service-principals-reference-table/) and also the action package that we get while deploying has the similar structure of Kaizala action. So we would like to know more about these details.

**Comment by yogesh-MS** [comment]
These Apps does not related to kaizala.
