### ISSUE TITLE
"error":"This service is not available in your location."

### ISSUE THREAD

**Issue by elbruno** [OfficeDev/microsoft-teams-apps-survey#3]
Hi

on the step [npm run deploy] I got the following error:

`> survey@1.0.0 zip D:\OneDrive\Avanade\FY21\2020 Ottawa IC\DemoTenant\microsoft-teams-apps-survey-main
> cd ./output && bestzip ./ActionPackage.zip *

Writing * to ./ActionPackage.zip...
zipped!
Log file path: D:\OneDrive\Avanade\FY21\2020 Ottawa IC\DemoTenant\microsoft-teams-apps-survey-main\output\survey.20_11_2020.log
Fetching zip upload url ...
Please login to your AAD account when prompted ...
Request details: TenantId: cd8b8212-1896-44f1-a00d-b8b36d23ced6, UserId: b9bfdd7f-3079-4096-8a51-28f6bfc76290, CorrelationId: 13654752-394a-4737-a236-0d4a9d8c1804, Timestamp: 2020-11-20T17:59:32.423Z
API response error: {"error":"This service is not available in your location.","correlationId":"13654752-394a-4737-a236-0d4a9d8c1804","serverCorrelationId":"c9bc8442-16cf-4c6d-b0ac-cc43d8d15c3e"}, status: 500, statusText: Internal Server Error
Failed to get zip upload url!`

How do I define a specific region, or which service is the one not available?

Thanks!

**Comment by yogesh-MS** [comment]
As per documentation, Service is not available in Canada region.
https://github.com/OfficeDev/microsoft-teams-apps-survey/wiki/Solution-overview
