### ISSUE TITLE
Upload failed! Error: The action package belongs to a different tenant!

### ISSUE THREAD

**Issue by ryanmck-msft** [OfficeDev/microsoft-teams-apps-survey#9]
Anyone have ideas for what may be causing this issue at the end of the npm run deploy command?

"Upload failed! Error: The action package belongs to a different tenant!, CorrelationId: d47e2561-845e-4e31-b7f2-d69c5819124f"

**Comment by YogeshIITK** [comment]
If user tenant and uploaded teams zip tenant is different then we got such error. Please use same tenant for providing permission to App and uploading the Teams app Zip.
